/// Une seule ligne : le contexte de la collecte lue.
/// 
/// ELLE EST AFFICHEE SUR CHAQUE PAGE, dans la barre de couverture. Un rapport
/// d'audit sans son instant d'extraction, sa fenetre et son serveur n'est pas
/// interpretable : le meme graphique ne dit pas la meme chose selon qu'il porte
/// sur sept jours ou sur un an, et selon qu'il a ete pris ce matin ou il y a
/// trois semaines.
/// 
/// Elle porte aussi les droits du compte utilise. Un compte membre de sysadmin
/// ou ssis_admin est signale : la collecte reste en lecture seule, mais la
/// protection repose alors sur la discipline et non sur les permissions, et
/// cela se dit au lecteur du rapport.
table Collecte
	lineageTag: 679e1786-009c-4885-a516-e6032422491e

	column ExtractionTimestampUtc
		dataType: dateTime
		formatString: General Date
		lineageTag: c3000000-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: ExtractionTimestampUtc

	column Serveur
		dataType: string
		lineageTag: c3000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: Serveur

	column ModeAuthentification
		dataType: string
		lineageTag: c3000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: ModeAuthentification

	column VersionModule
		dataType: string
		lineageTag: c3000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: VersionModule

	/// Largeur de la fenetre d'analyse en jours. VIDE = toute la retention du
	/// catalogue, ce qui n'est pas la meme chose qu'une fenetre longue : la
	/// retention se purge, et les executions les plus anciennes ont pu
	/// disparaitre.
	column FenetreJours
		dataType: int64
		lineageTag: c3000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: FenetreJours

	/// Borne basse EFFECTIVE, calculee sur l'heure du SERVEUR.
	/// 
	/// Elle l'a ete un temps sur l'horloge du poste d'audit, alors que
	/// l'instant d'extraction venait du serveur : "les 30 derniers jours" ne
	/// designaient pas les memes 30 jours que ceux que le serveur voit, et la
	/// borne se deplacait avec la derive de l'horloge du poste.
	column FenetreDebut
		dataType: dateTime
		formatString: General Date
		lineageTag: c3000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: FenetreDebut

	column ExecutionsDansFenetre
		dataType: int64
		formatString: #,0
		lineageTag: c3000000-0000-4000-8000-000000000007
		summarizeBy: sum
		sourceColumn: ExecutionsDansFenetre

	/// Niveaux de logging observes DANS LA FENETRE, pas sur toute la retention.
	/// La distinction compte : une execution Verbose vieille de six mois ne
	/// rend pas les statistiques de flux disponibles pour une fenetre de sept
	/// jours qui ne contient que du Basic.
	column NiveauxLoggingObserves
		dataType: string
		lineageTag: c3000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: NiveauxLoggingObserves

	column CompteAuxDroitsLarges
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: c3000000-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: CompteAuxDroitsLarges

	/// Vrai si le role ssis_logreader n'existe pas sur ce catalogue. Ce role
	/// est cite par la vue catalog.executions mais N'EST PAS CREE par SQL
	/// Server : son absence est la situation normale, et c'est elle qui oblige
	/// a demander sysadmin faute de mieux.
	column RoleLogreaderInexistant
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: c3000000-0000-4000-8000-000000000010
		summarizeBy: none
		sourceColumn: RoleLogreaderInexistant

	/// Nom du sous-dossier de collecte effectivement lu. A afficher tel quel :
	/// c'est la reference qui permet de retrouver les CSV d'origine.
	column NomCollecte
		dataType: string
		lineageTag: c3000000-0000-4000-8000-000000000011
		summarizeBy: none
		sourceColumn: NomCollecte

	column VersionPlan
		dataType: string
		lineageTag: e3b88c0e-3b44-40c0-b319-ebd50ef733b6
		summarizeBy: none
		sourceColumn: VersionPlan

		annotation SummarizationSetBy = Automatic

	partition Collecte = m
		mode: import
		source =
				let
				    Source = fnLireCsv(
				        "Run.csv",
				        {"ExtractionTimestampUtc", "Serveur", "ModeAuthentification",
				         "VersionModule", "VersionPlan", "FenetreJours", "FenetreDebut",
				         "ExecutionsDansFenetre", "NiveauxLoggingObserves",
				         "RoleLogreaderInexistant", "CompteAuxDroitsLarges"}),
				
				    Types = Table.TransformColumns(
				        Source,
				        {
				            {"FenetreJours",            each try Int64.From(_) otherwise null, Int64.Type},
				            {"ExecutionsDansFenetre",   each try Int64.From(_) otherwise null, Int64.Type},
				            {"CompteAuxDroitsLarges",   fnBooleen, type nullable logical},
				            {"RoleLogreaderInexistant", fnBooleen, type nullable logical},
				            {"ExtractionTimestampUtc",  fnHorodatage, type nullable datetimezone},
				            {"FenetreDebut",            fnHorodatage, type nullable datetimezone}
				        }),
				
				    // CES DEUX INSTANTS RESTENT EN UTC, ET ILS SONT AFFICHES COMME TELS.
				    //
				    // Contrairement aux tables de faits, Run.csv ne porte aucun
				    // decalage : rien ne permet de les ramener a l'heure de mur du
				    // serveur. Les convertir vers le fuseau du poste donnerait une
				    // heure d'apparence locale, fausse des que le poste et le serveur
				    // different - et impossible a distinguer d'une heure juste.
				    //
				    // Mieux vaut une heure UTC annoncee qu'une heure locale douteuse.
				    // Les mesures de bandeau ajoutent la mention "UTC".
				    Locales = Table.TransformColumns(
				        Types,
				        List.Transform(
				            {"ExtractionTimestampUtc", "FenetreDebut"},
				            each {_, (v) => if v = null then null else DateTimeZone.RemoveZone(v), type nullable datetime})),
				
				    AvecNom = Table.AddColumn(
				        Locales,
				        "NomCollecte",
				        each List.Last(List.RemoveItems(Text.Split(CheminCollecte, "\"), {""})),
				        type text)
				in
				    AvecNom

