/// Une ligne par executable - tache, conteneur, boucle - et par execution.
/// 
/// C'EST LA TABLE QUI DIT OU PART LE TEMPS A L'INTERIEUR D'UN PACKAGE, et elle
/// est disponible des le niveau Basic. Volumetrie mesuree : environ onze lignes
/// par execution sur un package trivial, beaucoup plus des qu'il y a des
/// boucles.
/// 
/// UNE BOUCLE PRODUIT UNE LIGNE PAR TOUR. Additionner les durees d'un
/// executable sans regarder NiveauxIteration additionne donc des tours, pas des
/// executions. C'est la premiere cause de double comptage sur ce grain.
/// 
/// LA HIERARCHIE EST OBSERVEE, JAMAIS DECLAREE. CheminExecution donne
/// l'imbrication reelle telle qu'elle s'est produite ; il ne prouve aucune
/// dependance de precedence entre packages lances separement. Le terme "chemin
/// critique" reste interdit sans l'audit statique des sources (decision D020).
table Executables
	lineageTag: b3f4f2e9-f02f-48c7-bb46-0bdd25b076f7

	column StatistiqueId
		dataType: int64
		isKey
		lineageTag: b2000000-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: StatistiqueId

	column ExecutionId
		dataType: int64
		lineageTag: b2000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: ExecutionId

	column Dossier
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: Dossier

	column Projet
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: Projet

	column Package
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: Package

	column PackageCle
		dataType: string
		isHidden
		lineageTag: b2000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: PackageCle

	/// Identifiant stable de la tache A TRAVERS LES VERSIONS du package. C'est
	/// lui qu'il faut pour suivre une tache dans le temps : son nom, lui,
	/// change au gre des renommages sans que la tache change.
	column ExecutableGuid
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: ExecutableGuid

	column Executable
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: Executable

	/// Chemin d'execution reel, avec les indices d'iteration des boucles.
	column CheminExecution
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: CheminExecution

	/// Chemin debarrasse des indices d'iteration : c'est lui qui regroupe les
	/// tours d'une meme boucle sous une seule tache.
	column CheminLogique
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000010
		summarizeBy: none
		sourceColumn: CheminLogique

	/// Nombre de niveaux de boucle au-dessus de cet executable. Zero = la tache
	/// n'a tourne qu'une fois dans l'execution.
	column NiveauxIteration
		dataType: int64
		lineageTag: b2000000-0000-4000-8000-000000000011
		summarizeBy: none
		sourceColumn: NiveauxIteration

	/// Faux si la normalisation du chemin logique n'a pas pu etre menee a son
	/// terme. Ces lignes ne doivent pas etre agregees par CheminLogique : leur
	/// regroupement serait approximatif, et rien ne le signalerait ensuite.
	column NormalisationComplete
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: b2000000-0000-4000-8000-000000000012
		summarizeBy: none
		sourceColumn: NormalisationComplete

	column Profondeur
		dataType: int64
		lineageTag: b2000000-0000-4000-8000-000000000013
		summarizeBy: none
		sourceColumn: Profondeur

	/// Vrai pour l'executable racine, celui dont la duree vaut celle du
	/// package entier. LE COMPTER AVEC SES ENFANTS COMPTE LE TEMPS DEUX FOIS :
	/// toute somme de durees sur cette table doit exclure la racine, ou ne
	/// garder qu'elle.
	column EstRacine
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: b2000000-0000-4000-8000-000000000014
		summarizeBy: none
		sourceColumn: EstRacine

	column HeureDebut
		dataType: dateTime
		formatString: General Date
		lineageTag: b2000000-0000-4000-8000-000000000015
		summarizeBy: none
		sourceColumn: HeureDebut

	column HeureFin
		dataType: dateTime
		formatString: General Date
		lineageTag: b2000000-0000-4000-8000-000000000016
		summarizeBy: none
		sourceColumn: HeureFin

	/// Duree en MILLISECONDES : le grain de la tache est bien plus fin que
	/// celui de l'execution, et beaucoup de taches durent moins d'une seconde.
	column DureeMillisecondes
		dataType: double
		formatString: #,0
		lineageTag: b2000000-0000-4000-8000-000000000017
		summarizeBy: sum
		sourceColumn: DureeMillisecondes

	column ResultatCode
		dataType: int64
		lineageTag: b2000000-0000-4000-8000-000000000018
		summarizeBy: none
		sourceColumn: ResultatCode

	column Resultat
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000019
		summarizeBy: none
		sourceColumn: Resultat

	column DecalageUtcMinutes
		dataType: double
		lineageTag: cae9e055-a3cc-4336-a4d0-217ad4272d13
		summarizeBy: sum
		sourceColumn: DecalageUtcMinutes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Executables = m
		mode: import
		source =
				let
				    Source = fnLireCsv(
				        "Executables.csv",
				        {"StatistiqueId", "ExecutionId", "Dossier", "Projet", "Package",
				         "ExecutableGuid", "Executable", "CheminExecution", "CheminLogique",
				         "NiveauxIteration", "NormalisationComplete", "Profondeur", "EstRacine",
				         "HeureDebut", "HeureFin", "DecalageUtcMinutes", "DureeMillisecondes",
				         "ResultatCode", "Resultat"}),
				
				    Types = Table.TransformColumns(
				        Source,
				        {
				            {"StatistiqueId",         each try Int64.From(_) otherwise null, Int64.Type},
				            {"ExecutionId",           each try Int64.From(_) otherwise null, Int64.Type},
				            {"NiveauxIteration",      each try Int64.From(_) otherwise null, Int64.Type},
				            {"Profondeur",            each try Int64.From(_) otherwise null, Int64.Type},
				            {"ResultatCode",          each try Int64.From(_) otherwise null, Int64.Type},
				            {"DureeMillisecondes",    fnNombre, type nullable number},
				            {"NormalisationComplete", fnBooleen, type nullable logical},
				            {"EstRacine",             fnBooleen, type nullable logical},
				            {"HeureDebut",            fnHorodatage, type nullable datetimezone},
				            {"HeureFin",              fnHorodatage, type nullable datetimezone},
				            {"DecalageUtcMinutes",    fnNombre, type nullable number}
				        }),
				
				    // Heure de mur DU SERVEUR, decalage pris par ligne. Voir fnHeureServeur :
				    // convertir vers le fuseau du poste d analyse mettrait ces heures en
				    // contradiction avec les colonnes de calendrier, calculees cote serveur.
				    Locales = fnHeuresServeurTable(Types, {"HeureDebut", "HeureFin"}, "DecalageUtcMinutes"),
				
				    AvecCle = Table.AddColumn(
				        Locales,
				        "PackageCle",
				        each fnClePackage([Dossier], [Projet], [Package]),
				        type text)
				in
				    AvecCle

