/// Une ligne par extraction du plan, y compris celles qui n'ont pas tourne.
/// 
/// C'EST LA TABLE QUI EMPECHE LE RAPPORT DE MENTIR.
/// 
/// Un visuel vide et une donnee absente se ressemblent a l'ecran. Sans cette
/// table, un graphique de phases de composants sans barres laisserait croire
/// qu'il n'y a rien a signaler, alors que le catalogue tourne en Basic et
/// n'a tout simplement jamais enregistre ces mesures.
/// 
/// Chaque page conditionnelle affiche donc son statut et son motif, lus ici.
/// C'est le pendant, cote restitution, du principe qui gouverne le runner :
/// une extraction en echec ne produit AUCUN fichier, plutot qu'un fichier
/// reduit a ses en-tetes.
/// 
/// SEPT STATUTS, EN LISTE FERMEE : ReussieAvecDonnees, ReussieVide,
/// NonSelectionnee, NonApplicable, Indisponible, VolumeExceedsLimit, Echec.
/// La distinction entre ReussieVide et Indisponible est le coeur du contrat :
/// "aucun resultat" et "pas de donnee disponible" sont deux constats opposes.
table Extractions
	lineageTag: ed285d12-1555-451f-8d14-7f2eb0b754f9

	column Cle
		dataType: string
		isKey
		lineageTag: c2000000-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: Cle

	column Nom
		dataType: string
		lineageTag: c2000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: Nom

	column Sortie
		dataType: string
		lineageTag: c2000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: Sortie

	column Statut
		dataType: string
		lineageTag: c2000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: Statut

	/// Vrai si l'operateur a nomme cette extraction. Une indisponibilite sur
	/// une extraction explicitement demandee est un ECHEC du run ; la meme
	/// indisponibilite sous -Tout est un simple constat de catalogue.
	column DemandeeExplicitement
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: c2000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: DemandeeExplicitement

	column Lignes
		dataType: int64
		formatString: #,0
		lineageTag: c2000000-0000-4000-8000-000000000006
		summarizeBy: sum
		sourceColumn: Lignes

	column LignesEstimees
		dataType: int64
		formatString: #,0
		lineageTag: c2000000-0000-4000-8000-000000000007
		summarizeBy: sum
		sourceColumn: LignesEstimees

	column DureeSecondes
		dataType: double
		formatString: #,0.##
		lineageTag: c2000000-0000-4000-8000-000000000008
		summarizeBy: sum
		sourceColumn: DureeSecondes

	/// Motif rendu par le runner. C'est ce texte qui s'affiche a la place d'un
	/// visuel vide.
	column Message
		dataType: string
		lineageTag: c2000000-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: Message

	/// Regroupement d'affichage : Produite, Vide, Indisponible, Ecartee,
	/// RefuseePourVolume, Echec.
	/// 
	/// LES SIX CATEGORIES RESTENT DISTINCTES, ET IL A FALLU S'Y REPRENDRE.
	/// Une premiere version rangeait "refusee pour volume" et "echec" avec
	/// "indisponible". Ce sont pourtant trois situations qui appellent trois
	/// actions differentes : monter le niveau de logging, reduire la fenetre,
	/// ou comprendre une panne. Les confondre dans un visuel ferait exactement
	/// ce que la matrice de capacites interdit - presenter comme equivalents
	/// des constats qui ne le sont pas.
	/// 
	/// La logique fine reste sur Statut, qui est la liste fermee du contrat.
	column Categorie
		dataType: string
		lineageTag: c2000000-0000-4000-8000-000000000010
		summarizeBy: none
		sourceColumn: Categorie

	column Fichier
		dataType: string
		lineageTag: dd40714e-fad8-4e55-bd05-8bbd8b37b4d7
		summarizeBy: none
		sourceColumn: Fichier

		annotation SummarizationSetBy = Automatic

	partition Extractions = m
		mode: import
		source =
				let
				    Source = fnLireCsv(
				        "Extractions.csv",
				        {"Cle", "Nom", "Fichier", "Sortie", "DemandeeExplicitement",
				         "Statut", "Lignes", "LignesEstimees", "DureeSecondes", "Message"}),
				
				    Types = Table.TransformColumns(
				        Source,
				        {
				            {"Lignes",                each try Int64.From(_) otherwise null, Int64.Type},
				            {"LignesEstimees",        each try Int64.From(_) otherwise null, Int64.Type},
				            {"DureeSecondes",         fnNombre, type nullable number},
				            {"DemandeeExplicitement", fnBooleen, type nullable logical}
				        }),
				
				    Categorisee = Table.AddColumn(
				        Types,
				        "Categorie",
				        each if [Statut] = "ReussieAvecDonnees"  then "Produite"
				             else if [Statut] = "ReussieVide"        then "Vide"
				             else if [Statut] = "Indisponible"       then "Indisponible"
				             else if [Statut] = "NonApplicable"      then "Indisponible"
				             else if [Statut] = "NonSelectionnee"    then "Ecartee"
				             else if [Statut] = "VolumeExceedsLimit" then "RefuseePourVolume"
				             else if [Statut] = "Echec"              then "Echec"
				             else "Echec",
				        type text)
				in
				    Categorisee

