/// Une ligne par phase de composant de flux de donnees.
/// 
/// EXIGE LE LOGGING PERFORMANCE AU MINIMUM. Sur un catalogue en Basic, cette
/// table est VIDE et elle doit le rester : la page qui s'en sert affiche alors
/// son motif d'indisponibilite, jamais un visuel vide. Un visuel vide et une
/// absence de donnee se ressemblent a l'ecran et ne veulent pas du tout dire la
/// meme chose.
/// 
/// C'EST LA TABLE LA PLUS VOLUMINEUSE DU MODELE : 243 lignes par execution,
/// mesurees sur un package trivial a boucle de dix tours. Vingt-deux fois le
/// grain des executables, deux cent quarante-trois fois celui des executions.
/// Le runner la refuse au-dela de deux millions de lignes plutot que de la
/// tronquer.
table PhasesComposants
	lineageTag: a739b47b-3caf-4b6f-9104-e808b80bfc7c

	column PhaseId
		dataType: int64
		isKey
		lineageTag: b4000000-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: PhaseId

	column ExecutionId
		dataType: int64
		lineageTag: b4000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: ExecutionId

	column PackageCle
		dataType: string
		isHidden
		lineageTag: b4000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: PackageCle

	column Package
		dataType: string
		lineageTag: b4000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: Package

	column Tache
		dataType: string
		lineageTag: b4000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: Tache

	column SousComposant
		dataType: string
		lineageTag: b4000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: SousComposant

	/// Nom de la phase : AcquireConnections, PreExecute, ProcessInput,
	/// PostExecute... LES PHASES SE CHEVAUCHENT ENTRE COMPOSANTS d'un meme
	/// flux, par construction : un pipeline traite en parallele. Additionner
	/// leurs durees donne un total superieur a la duree du flux, et ce total
	/// ne represente rien.
	column Phase
		dataType: string
		lineageTag: b4000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: Phase

	column HeureDebut
		dataType: dateTime
		formatString: General Date
		lineageTag: b4000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: HeureDebut

	column HeureFin
		dataType: dateTime
		formatString: General Date
		lineageTag: b4000000-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: HeureFin

	column DureeMillisecondes
		dataType: double
		formatString: #,0
		lineageTag: b4000000-0000-4000-8000-000000000010
		summarizeBy: sum
		sourceColumn: DureeMillisecondes

	column DecalageUtcMinutes
		dataType: double
		lineageTag: 128f8d89-da5e-4460-9107-973552301197
		summarizeBy: sum
		sourceColumn: DecalageUtcMinutes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition PhasesComposants = m
		mode: import
		source =
				let
				    Source = fnLireCsv(
				        "PhasesComposants.csv",
				        {"PhaseId", "ExecutionId", "Dossier", "Projet", "Package",
				         "Tache", "SousComposant", "Phase", "HeureDebut", "HeureFin",
				         "DecalageUtcMinutes"}),
				
				    Types = Table.TransformColumns(
				        Source,
				        {
				            {"PhaseId",     each try Int64.From(_) otherwise null, Int64.Type},
				            {"ExecutionId", each try Int64.From(_) otherwise null, Int64.Type},
				            {"HeureDebut",  fnHorodatage, type nullable datetimezone},
				            {"HeureFin",    fnHorodatage, type nullable datetimezone},
				            {"DecalageUtcMinutes", fnNombre, type nullable number}
				        }),
				
				    // La duree se calcule ICI, sur les valeurs a decalage connu, et
				    // AVANT de retirer le fuseau. Une phase qui enjambe un changement
				    // d'heure donnerait sinon une duree fausse d'une heure - ou
				    // negative au passage a l'heure d'ete.
				    AvecDuree = Table.AddColumn(
				        Types,
				        "DureeMillisecondes",
				        each if [HeureDebut] = null or [HeureFin] = null then null
				             else Duration.TotalSeconds([HeureFin] - [HeureDebut]) * 1000,
				        type nullable number),
				
				    // Heure de mur DU SERVEUR, decalage pris par ligne. La duree a deja ete
				    // calculee plus haut, sur les instants absolus : un changement de fuseau
				    // ne deplace pas un instant, donc elle reste juste.
				    Locales = fnHeuresServeurTable(AvecDuree, {"HeureDebut", "HeureFin"}, "DecalageUtcMinutes"),
				
				    AvecCle = Table.AddColumn(
				        Locales,
				        "PackageCle",
				        each fnClePackage([Dossier], [Projet], [Package]),
				        type text),
				
				    Final = Table.RemoveColumns(AvecCle, {"Dossier", "Projet"})
				in
				    Final

