/// Une ligne par chemin de flux de donnees mesure : combien de lignes ont
/// transite entre deux composants.
/// 
/// EXIGE LE LOGGING VERBOSE. C'est le niveau le plus couteux du catalogue, et
/// il n'est presque jamais actif en production continue. Sur un catalogue en
/// Basic ou Performance, cette table est vide, et la page le dit avec son
/// motif.
/// 
/// LIGNES TRANSMISES N'EST PAS UN DEBIT. Le catalogue donne un COMPTE de
/// lignes sur un chemin, associe a un instant de mesure. Il ne donne ni la
/// duree du transfert ni un taux. Diviser ce compte par la duree du flux
/// fabriquerait un debit moyen qui n'a ete mesure nulle part - c'est
/// explicitement classe "non mesurable dans ce contexte" sur la page Qualite.
table StatistiquesFlux
	lineageTag: ebd35801-5df2-476d-aa12-b4f3ab428620

	column StatistiqueFluxId
		dataType: int64
		isKey
		lineageTag: b5000000-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: StatistiqueFluxId

	column ExecutionId
		dataType: int64
		lineageTag: b5000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: ExecutionId

	column PackageCle
		dataType: string
		isHidden
		lineageTag: b5000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: PackageCle

	column Package
		dataType: string
		lineageTag: b5000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: Package

	column Tache
		dataType: string
		lineageTag: b5000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: Tache

	column CheminFlux
		dataType: string
		lineageTag: b5000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: CheminFlux

	column ComposantSource
		dataType: string
		lineageTag: b5000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: ComposantSource

	column ComposantDestination
		dataType: string
		lineageTag: b5000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: ComposantDestination

	/// Compte de lignes ayant transite sur ce chemin. Voir l'avertissement en
	/// tete de table : ce n'est pas un debit.
	column LignesTransmises
		dataType: int64
		formatString: #,0
		lineageTag: b5000000-0000-4000-8000-000000000009
		summarizeBy: sum
		sourceColumn: LignesTransmises

	column HeureMesure
		dataType: dateTime
		formatString: General Date
		lineageTag: b5000000-0000-4000-8000-000000000010
		summarizeBy: none
		sourceColumn: HeureMesure

	column DecalageUtcMinutes
		dataType: double
		lineageTag: 0f6458db-25fc-4ced-9116-c99ba7f5e3e3
		summarizeBy: sum
		sourceColumn: DecalageUtcMinutes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition StatistiquesFlux = m
		mode: import
		source =
				let
				    Source = fnLireCsv(
				        "StatistiquesFlux.csv",
				        {"StatistiqueFluxId", "ExecutionId", "Dossier", "Projet", "Package",
				         "Tache", "CheminFlux", "ComposantSource", "ComposantDestination",
				         "LignesTransmises", "HeureMesure", "DecalageUtcMinutes"}),
				
				    Types = Table.TransformColumns(
				        Source,
				        {
				            {"StatistiqueFluxId", each try Int64.From(_) otherwise null, Int64.Type},
				            {"ExecutionId",       each try Int64.From(_) otherwise null, Int64.Type},
				            {"LignesTransmises",  each try Int64.From(_) otherwise null, Int64.Type},
				            {"HeureMesure",       fnHorodatage, type nullable datetimezone},
				            {"DecalageUtcMinutes", fnNombre, type nullable number}
				        }),
				
				    // Heure de mur DU SERVEUR, decalage pris par ligne. Voir fnHeureServeur.
				    Locales = fnHeuresServeurTable(Types, {"HeureMesure"}, "DecalageUtcMinutes"),
				
				    AvecCle = Table.AddColumn(
				        Locales,
				        "PackageCle",
				        each fnClePackage([Dossier], [Projet], [Package]),
				        type text),
				
				    Final = Table.RemoveColumns(AvecCle, {"Dossier", "Projet"})
				in
				    Final

