/// Une ligne par version de projet connue du catalogue.
/// 
/// ELLE SERT A DATER LES DEPLOIEMENTS SUR LES COURBES DE DUREE. C'est le
/// repere le plus utile d'une analyse de derive : une rupture de duree qui
/// coincide avec un deploiement oriente immediatement l'investigation.
/// 
/// UNE COINCIDENCE N'EST PAS UNE CAUSE, et le rapport doit l'ecrire.
/// Un deploiement qui precede une degradation peut l'avoir causee, ou avoir
/// eu lieu le meme jour qu'un changement de volume, de plan d'execution ou
/// d'infrastructure. Le catalogue ne permet pas de trancher. La maquette
/// porte cette phrase en clair sous le graphique, et elle doit y rester.
/// 
/// LA DATE DE DEPLOIEMENT EST SOUVENT UN ENCADREMENT, PAS UNE DATE.
/// Le catalogue ne l'horodate pas directement pour toutes les versions. Elle
/// est alors bornee entre deux instants connus, et IncertitudeHeures dit la
/// largeur de cet encadrement. Afficher la borne sans l'incertitude
/// donnerait une precision qu'on n'a pas.
table VersionsProjet
	lineageTag: 66582130-4a92-44ca-83af-4f22891a32ff

	column Dossier
		dataType: string
		lineageTag: c6000000-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: Dossier

	column Projet
		dataType: string
		lineageTag: c6000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: Projet

	column VersionProjetLsn
		dataType: int64
		lineageTag: c6000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: VersionProjetLsn

	/// Vrai si des executions de cette version figurent dans la fenetre. Une
	/// version connue du catalogue mais jamais observee n'a aucune duree a
	/// montrer, et ce n'est pas une anomalie.
	column ObserveeDansFenetre
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: c6000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: ObserveeDansFenetre

	column EstVersionCourante
		dataType: boolean
		formatString: """Vrai"";""Vrai"";""Faux"""
		lineageTag: c6000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: EstVersionCourante

	column DateDeploiement
		dataType: dateTime
		formatString: General Date
		lineageTag: c6000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: DateDeploiement

	/// Comment la date de deploiement est connue. A afficher a cote de la date
	/// des qu'elle n'est pas une mesure directe.
	column PreuveDeploiement
		dataType: string
		lineageTag: c6000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: PreuveDeploiement

	/// Largeur de l'encadrement, en heures. Zero ou vide = date mesuree.
	column IncertitudeHeures
		dataType: double
		formatString: #,0.##
		lineageTag: c6000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: IncertitudeHeures

	column NombreExecutions
		dataType: int64
		formatString: #,0
		lineageTag: c6000000-0000-4000-8000-000000000009
		summarizeBy: sum
		sourceColumn: NombreExecutions

	column PremiereExecution
		dataType: dateTime
		formatString: General Date
		lineageTag: c6000000-0000-4000-8000-000000000010
		summarizeBy: none
		sourceColumn: PremiereExecution

	column DerniereExecution
		dataType: dateTime
		formatString: General Date
		lineageTag: c6000000-0000-4000-8000-000000000011
		summarizeBy: none
		sourceColumn: DerniereExecution

	column DureeVieJours
		dataType: double
		formatString: #,0.#
		lineageTag: c6000000-0000-4000-8000-000000000012
		summarizeBy: none
		sourceColumn: DureeVieJours

	partition VersionsProjet = m
		mode: import
		source =
				let
				    Source = fnLireCsv(
				        "VersionsProjet.csv",
				        {"Dossier", "Projet", "VersionProjetLsn", "ObserveeDansFenetre",
				         "EstVersionCourante", "DateDeploiement", "PreuveDeploiement",
				         "IncertitudeHeures", "NombreExecutions", "PremiereExecution",
				         "DerniereExecution", "DureeVieJours"}),
				
				    Types = Table.TransformColumns(
				        Source,
				        {
				            {"VersionProjetLsn",    each try Int64.From(_) otherwise null, Int64.Type},
				            {"NombreExecutions",    each try Int64.From(_) otherwise null, Int64.Type},
				            {"IncertitudeHeures",   fnNombre, type nullable number},
				            {"DureeVieJours",       fnNombre, type nullable number},
				            {"ObserveeDansFenetre", fnBooleen, type nullable logical},
				            {"EstVersionCourante",  fnBooleen, type nullable logical},
				            {"DateDeploiement",     fnHorodatage, type nullable datetimezone},
				            {"PremiereExecution",   fnHorodatage, type nullable datetimezone},
				            {"DerniereExecution",   fnHorodatage, type nullable datetimezone}
				        }),
				
				    // CETTE TABLE N A PAS DE DECALAGE PAR LIGNE : 16_versions.sql ne l emet
				    // pas, contrairement aux cinq extractions de faits. On applique donc le
				    // decalage de reference de la collecte.
				    //
				    // L approximation est bornee a une heure, et seulement pour un
				    // deploiement situe de l autre cote d un changement d heure. Elle porte
				    // sur des REPERES deja presentes comme un encadrement, avec leur
				    // incertitude en heures. Aucune duree n en depend.
				    //
				    // La vraie correction est en amont, dans la requete. Point ouvert.
				    Locales = Table.TransformColumns(
				        Types,
				        List.Transform(
				            {"DateDeploiement", "PremiereExecution", "DerniereExecution"},
				            each {_, (v) => fnHeureServeur(v, DecalageReferenceMinutes), type nullable datetime}))
				in
				    Locales

